//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacSi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BacSi()
        {
            this.DatLichKhams = new HashSet<DatLichKham>();
            this.TuVans = new HashSet<TuVan>();
        }
    
        public int MaBacSi { get; set; }
        public int MaChuyenKhoa { get; set; }
        public string TenBacSi { get; set; }
        public string Tuoi { get; set; }
        public string Anh { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string TrinhDo { get; set; }
        public string KinhNghiem { get; set; }
    
        public virtual ChuyenKhoa ChuyenKhoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatLichKham> DatLichKhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TuVan> TuVans { get; set; }
    }
}
