//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatLichKham
    {
        public int MaDatLich { get; set; }
        public int MaDichVu { get; set; }
        public int MaBenhNhan { get; set; }
        public int MaBacSi { get; set; }
        public Nullable<System.DateTime> NgayDatLich { get; set; }
        public string TrieuChung { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual BacSi BacSi { get; set; }
        public virtual BenhNhan BenhNhan { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
