//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoBenhAn
    {
        public int MaHoSo { get; set; }
        public Nullable<int> MaBenhNhan { get; set; }
        public Nullable<System.DateTime> NgayNhapVien { get; set; }
        public Nullable<System.DateTime> NgayXuatVien { get; set; }
        public string TomTatBenhAn { get; set; }
        public Nullable<int> MaNguoiThan { get; set; }
    
        public virtual BenhNhan BenhNhan { get; set; }
        public virtual NguoiThan NguoiThan { get; set; }
    }
}
